### ISSUE TITLE
feedrapp.info not working

### ISSUE THREAD

**Issue by pstadt** [sdepold/feedrapp#111] opened 2023-05-14 06:53 UTC
Hello

looks like www.feedrapp.info does not resolve anymore.
Nameservers are set, but they do not deliver useful content.

```
$ host -tNS  feedrapp.info 
feedrapp.info name server lila.ns.cloudflare.com.
feedrapp.info name server norm.ns.cloudflare.com.
$ host  feedrapp.info 
$ host  www.feedrapp.info 
Host www.feedrapp.info not found: 3(NXDOMAIN)
```

**Comment by ahmogit** [comment] 2023-05-14 16:12
Confirmed.  

Also, a recent addition to the README.md from the `sdepold/jquery-rss` repo (posted May 13, 2023) seems to imply that feedrapp.info is not coming back. 

Also, somewhat amusingly, that same README.md points to this repo  (`sdepold/feedrapp`), which, under the **Documentation** subheading of its own README.md, says `Please see https://feedrapp.info for further information.` 

I have no clue as to what to do here, other than attempting to host the service myself, which seems like it could easily turn into a bloatfest.

Any suggestions would be appreciated.

**Comment by ahmogit** [comment] 2023-05-16 14:22
@codem0de fyi: I attempted to build it locally in accordance with the README.md, but 
no joy. See attached example log from the make run.   

[example_log.txt](https://github.com/sdepold/feedrapp/files/11488771/example_log.txt)

I didn't attempt to dig in and address any of the build errors because my familiarity with JS is limited, so possibly it may be a relatively simple matter to cure. But it did have the look of out-of-date dependency issue(s).

**Comment by sdepold** [comment] 2023-05-21 14:53
I didn't really expect anyone to miss the app. Let me write something down on how to get it released to a self-owned service.

**Comment by sdepold** [comment] 2023-05-21 15:14
I would assume that the free usage limits of Vercel are reached very soon but for the moment we have 

https://www.feedrapp.info for the website
https://www.feedrapp.info/api?q=https%3A%2F%2Fbitte.kaufen%2Fmagazin%2Ffeed%2F and for the API endpoint

**Comment by sdepold** [comment] 2023-05-21 15:33
Hosting instructions are here:

https://www.feedrapp.info/hosting
https://github.com/sdepold/feedrapp/blob/master/pages/hosting.mdx

**Comment by codem0de** [comment] 2023-05-21 16:08
Thanks a ton! I think I can get it working.

**Comment by codem0de** [comment] 2023-05-21 16:21
Works. Thank you so much @sdepold!

**Comment by ahmogit** [comment] 2023-05-21 17:33
Thanks @sdepold.  Confirm workingness now with the temp modified API URL. Hopefully that stays up long enough for me to understand how to self-host it on a permanent basis, based on your instructions.  

The interesting sub-question is: If an outfit like Vercel permits N users to free-self-host the identical app, how is that an improvement for them (in terms of their resources) over just having one self-hoster that permits free accesses from N users?   

Anyway, I guess that's looking a gift horse in the mouth, so I'll be quiet. :)

**Comment by sdepold** [comment] 2023-05-21 17:37
Actually the latest master should work as before (without the need for /api). It will forward the request as needed

**Comment by sdepold** [comment] 2023-05-21 17:38
Question for you: are you using feedrapp standalone or through some js client?

**Comment by sdepold** [comment] 2023-05-21 17:40
Actually 🤔 maybe we can convince vercel that the project is open source and that we get unlimited hosting

**Comment by sdepold** [comment] 2023-05-21 17:42
Will have a look into this later :)

**Comment by ahmogit** [comment] 2023-05-21 17:47
@sdepold wrote:
>
> Actually the latest master should work as before (without the need for /api). It will forward the request as needed.
>

Indeed it does, thanks.

>
> are you using feedrapp standalone or through some js client?
>

I'm accessing feedrapp via a script called jquery.rss.js, which I have no memory anymore of where it came from.

**Comment by sdepold** [comment] 2023-05-21 18:03
Gotcha. That is my lib too 😂

https://github.com/sdepold/jquery-rss

**Comment by sdepold** [comment] 2023-05-21 19:20
Free plan is already depleted. However, I have reached out to Vercel now. Let's see what will come out of this.

**Comment by ahmogit** [comment] 2023-05-21 19:36
Any stats available showing how many accesses occurred during the few hours when it was active? That might give a clue as to what kind of costs might be involved if it were to transition to a subscription service.

**Comment by ahmogit** [comment] 2023-05-23 11:18
**@sdepoold**:
>
> Free plan is already depleted. However, I have reached out to Vercel now. Let's see what will come out of this.
>

Any update on this? Has Vercel responded?  The (fixed) README still says "hosted by Vercel" but the URL has been returning  "service disabled, payment required" since the free resource limit was hit a few days ago (as you said).

Also: Instructions for local build seem to have disappeared from the README.md. I'd like to take another shot at that, but really need the instructions in order to do so.

**Comment by ahmogit** [comment] 2023-05-23 21:37
OK, thanks. I was able to get the yarn-based build to work, and have it running locally now.   So I won't harass you any further about Vercel. :)  Thanks very much for your responsive help on this. 

As a side note for anyone else who may be going this route: Evidently the yarn-built "production" version defaults to http (rather than https, as on the public now-defunct  feedrapp.info version) so you'll have to account for this in the URL that you provide. That was the only wrinkle that I ran into. Other than that, it more or less "just worked" from the yarn build forward. On my system, it was indeed a bit of a bloatfest (~600 MB) but that may be due to the fact that I had very little JS infrastructure installed to begin with, so the dependency satisfaction chain brought in a lot of 'new' JS packages.

**Comment by sdepold** [comment] 2023-05-24 09:18
Yeah that's a Node thing. Some more pointers for those who might want to build a minimal Docker image or something:

https://github.com/tj/node-prune
also: `npm prune --production`

**Comment by sdepold** [comment] 2023-08-31 18:42
FWIW: After a bit of chatting with different people, I'm bringing the server back online. It probably works as of now already. I'm going to do some more improvements going forward

**Comment by sdepold** [comment] 2023-09-16 04:56
Closing this since we are back on track :)

**Closed** 2023-09-16 04:56 UTC
